name: AI-Powered Email Responder

on:
  schedule:
    - cron: '0 * * * *'  # Run the action every hour
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  email-responder:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir google-api-python-client google-auth-httplib2 google-auth-oauthlib openai

    # Set up Gmail API credentials and OpenAI API key
    - name: Set up credentials and environment variables
      run: |
        echo "$GMAIL_API_CREDENTIALS" > credentials.json
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV

    # Run the Python script to handle emails
    - name: Run Email Responder Script
      run: |
        python responder.py

