name: Intelligent Email Responder

on:
  push:
    branches:
      - main  
  schedule:
    # Runs once a week at midnight on Sunday
    - cron: '0 0 * * 0'  # This will run every Sunday at midnight (UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  respond_to_emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run email responder script
        run: python src/email_responder.py
        env:
          GMAIL_API_CREDENTIALS: ${{ secrets.GMAIL_API_CREDENTIALS }}
          GROQ_LLAMMA_API_KEY: ${{ secrets.GROQ_LLAMMA_API_KEY }}